Resolved KeyError: 'L1_METADATA_FILE' from Landsat 8
mapbox/rio-toa pull request #36
Opened 2021-11-24 18:10 UTC by SimonMolinsky

Package can read parameters from MTL files with the 'LANDSAT_METADATA_FILE' group. It is related to the Issue: https://github.com/mapbox/rio-toa/issues/35

Tests are passing and now it is possible to read MTL files with 'LANDSAT_METADATA_FILE' header. I've tested `calculate_landsat_reflectance` from the scene LC08_L1TP_188018_20200927_20201005_02_T1 and it works well.

2021-11-24 18:29 UTC, dnomadb requested changes
@SimonMolinsky thanks for this PR -- it looks good to me. However could you remove the `.idea` config files from the PR (perhaps add `.idea` to the gitignore?

Thank you!

2021-11-24 19:39 UTC, SimonMolinsky commented
Hi @dnomadb ,

I've removed .idea folder (it is PyCharm specific). Hope it's 👌

2021-11-28 22:24 UTC, jaimebayes commented
Hi Simon, 

Thanks for the advice about the fix of this error, but I got another one also related with metadata, it seems like metadata does not have that field ('PRODUCT_METADATA'), btw my rio-toa version is 0.3.0.

-> 164     date_collected = metadata['PRODUCT_METADATA']['DATE_ACQUIRED']
    165     time_collected_utc = metadata['PRODUCT_METADATA']['SCENE_CENTER_TIME']
    166 

KeyError: 'PRODUCT_METADATA'

Any advice or suggestion will be welcome, 

Thanks, JL

2021-11-29 08:09 UTC, SimonMolinsky commented
@jaimebayes could you send me the MTL file you use and share your code that throws this error? It'll be easier for me to debug.

2021-11-29 16:12 UTC, jaimebayes commented
Hi Simon,

Sure, but I do not know how to attach files here. Could you explain me how to share the two text files? (metadata and code)

Thanks, JL

2021-11-29 21:46 UTC, jaimebayes commented
Hi Simon, 

Thanks for instructions to upload files, I attached the two files (metadata & code)
Any advice will be welcome,

JL
[code.txt](https://github.com/mapbox/rio-toa/files/7621349/code.txt)
[LC08_L1TP_009057_20141023_20200910_02_T1_MTL.txt](https://github.com/mapbox/rio-toa/files/7621350/LC08_L1TP_009057_20141023_20200910_02_T1_MTL.txt)

2021-12-08 17:27 UTC, jaimebayes commented
Sorry Simon, 

After running the code, it continue showing the same key error, I imported the packages directly from github, I don't know if I am missing something.

   `163   E = `metadata['IMAGE_ATTRIBUTES']['SUN_ELEVATION']`
`--> 164     date_collected = metadata['PRODUCT_METADATA']['DATE_ACQUIRED']`
   ` 165     time_collected_utc = metadata['PRODUCT_METADATA']['SCENE_CENTER_TIME']`

KeyError: 'PRODUCT_METADATA'

Any other advice or suggestion, JL

2021-12-15 21:07 UTC, SimonMolinsky commented
Hi @jaimebayes ,

Did you installed package from here: https://github.com/SimonMolinsky/rio-toa/tree/metadata-L1_METADATA_FILE-key-error ? It is branch with the correct version of algorithm (It is important to use code from the branch `metadata-L1_METADATA_FILE-key-error` from my Github and not from the `main` branch). Until PR is not accepted here you cannot install package from the official mapbox repo and see the changes.

2022-04-27 21:05 UTC, penntaylor commented
@dnomadb  What needs to happen to get this PR reviewed (again) and merged? rio_toa does not currently function for its main purpose with any of the imagery available via USGS's commercial cloud access because of this MTL issue.

2022-04-28 06:20 UTC, SimonMolinsky commented
@penntaylor Could you point me into the documentation of those MTL files or send me one as an example? I can check again this piece of code and prepare it to work against multiple versions of a metadata structure.

2022-04-28 20:51 UTC, penntaylor commented
@SimonMolinsky The commit your PR is based on is working correctly to process Landsat Collection 2 imagery. I just want mapbox to go ahead and merge your PR and push out a new rio_toa package to PyPi.

2022-05-06 20:23 UTC, alecglen commented
@dnomadb anything holding this up? It would be a big help for me too 🙏

2022-05-12 17:26 UTC, alecglen commented
@mpulkki-mapbox just pinging you because you're at least active in other mapbox repos, feel free to pass this off if there's someone more appropriate. What can we do to get this merged and released? The package is unusable in its current state.

2022-05-13 07:19 UTC, mpulkki-mapbox commented
> @mpulkki-mapbox just pinging you because you're at least active in other mapbox repos, feel free to pass this off if there's someone more appropriate. What can we do to get this merged and released? The package is unusable in its current state.

Hi @alecglen, I'll try to pass this forward :+1:

2022-05-24 14:08 UTC, SimonMolinsky commented
Hi @mpulkki-mapbox ,

Is this repo managed only by the organization or is there a way to join as a maintainer? Then I can take care for this PR; moreover I can take a look into other Issues. Is this package abandoned beacuse of the available data of Level 2?

2025-11-12 09:30 UTC, closed without merging